site_name: DJAM

repo_url: https://github.com/geosolutions-it/djam
repo_name: djam

site_description: Identity provider and Access manager for Django

site_author: GeoSolutions

nav:
  - Home: 'index.md'
  - API Keys: 'api-keys.md'
  - Integration with GeoServer: 'integration-with-geoserver.md'
  - REST API: 'rest-api'

theme:
  name: material
  palette:
    primary: green
    accent: purple
    scheme: preference
  icon:
    repo: fontawesome/brands/github
    logo: material/lock